version: "3.4"
services:
  db:
    image: mysql:latest
    container_name: service-quotes-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service_quotes
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app

  api:
    container_name: service-quotes-api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: service_quotes
      APP_SECRET: 98629fefcf93d958d829bffe8db3152cb579f7e384ac6246
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app

  web:
    container_name: service-quotes-web
    depends_on:
      - db
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      args:
        REACT_APP_API_URL: http://localhost:3000
    restart: always
    ports:
      - "3001:80"
    networks:
      - app

networks:
  app:

volumes:
  mysqldata:
